//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDeDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public int Id { get; set; }
        public int TimeId { get; set; }
        public string Nome { get; set; }
        public int NumeroDaCamisa { get; set; }
        public System.DateTime DataNascimento { get; set; }
    
        public virtual Time Time { get; set; }
    }
}
